CREATE TABLE "SponsorList" (
	"sponsorID"	INTEGER UNIQUE,
	"sponsorName"	TEXT,
	"sponsorPhone"	TEXT,
	"sponsorAddress"	TEXT,
	PRIMARY KEY("sponsorID")
);

INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('1', 'Revkah Bleaden', '292-328-5024', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('2', 'Debor Ruggs', '689-840-9916', 'Cyprus');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('3', 'Alicia Gaudin', '448-888-1246', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('4', 'Alvinia Dandy', '870-263-9868', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('5', 'Jerrilyn Worms', '992-340-8481', 'Iran');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('6', 'Mikey Kachel', '835-804-4389', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('7', 'Ruthy Barrie', '741-625-4330', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('8', 'Carolyne Lundbech', '791-712-7238', 'Philippines');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('9', 'Jo-anne Heckney', '552-317-8966', 'Nigeria');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('10', 'Sheila-kathryn Anyene', '560-492-8113', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('11', 'Lotte Le Fevre', '480-241-7076', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('12', 'Kincaid Dellatorre', '402-768-3670', 'Poland');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('13', 'Calvin Fever', '921-669-8931', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('14', 'Forrest Becraft', '469-891-6784', 'Philippines');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('15', 'Kimmi Cockshoot', '547-566-0078', 'Croatia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('16', 'Cathrine Scay', '966-634-3489', 'Ecuador');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('17', 'Ciel Sturzaker', '732-883-4806', 'Portugal');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('18', 'Julienne Bigglestone', '392-410-1295', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('19', 'Burgess Aloigi', '457-569-0958', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('20', 'Krystyna Ivimy', '509-467-6778', 'Brazil');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('21', 'Cobby Crawcour', '631-912-9893', 'Czech Republic');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('22', 'Annabell Siely', '557-811-9914', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('23', 'Corbet Spering', '576-840-6947', 'Russia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('24', 'Kaylil Conley', '293-669-6657', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('25', 'Corabelle Paddell', '702-527-9479', 'Russia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('26', 'Beilul Ternent', '365-360-1492', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('27', 'Mable Gallaher', '757-613-0973', 'United States');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('28', 'Waylan Macconaghy', '343-396-7354', 'Yemen');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('29', 'Rosaleen Hinstridge', '856-919-6390', 'Canada');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('30', 'Sebastiano Rennix', '674-383-4314', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('31', 'Alano Bissill', '771-284-2870', 'Portugal');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('32', 'Valera Furlonge', '491-948-0009', 'Portugal');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('33', 'Tim Spellicy', '255-765-5989', 'Syria');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('34', 'Georgeanne Laidlaw', '618-965-2579', 'Pakistan');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('35', 'Clemmie Kaiser', '294-975-7665', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('36', 'Vinson Spillane', '619-135-1261', 'United States');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('37', 'Cicily Driutti', '804-530-5726', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('38', 'Kennith Garrad', '256-661-9480', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('39', 'Sib Gadesby', '460-681-7158', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('40', 'Tine Bandt', '954-720-4027', 'Yemen');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('41', 'Sherill Surgood', '858-466-6416', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('42', 'Maureene Langstone', '712-123-4585', 'Brazil');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('43', 'Lesly Pepye', '266-845-8715', 'Democratic Republic of the Congo');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('44', 'Abra Do', '818-514-8710', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('45', 'Blinny Rarity', '675-908-0201', 'Poland');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('46', 'Iver Newcome', '317-652-9388', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('47', 'Harman Beauly', '467-998-5199', 'Greece');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('48', 'Cassie Burnham', '376-416-3565', 'Serbia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('49', 'Andeee Kevern', '520-510-7019', 'Philippines');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('50', 'Joceline Weaving', '147-728-8999', 'Thailand');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('51', 'Madison Olenin', '102-469-9666', 'Ivory Coast');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('52', 'Mella Lettington', '208-851-9493', 'Palestinian Territory');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('53', 'Erwin Roundtree', '898-137-5307', 'Brazil');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('54', 'Saundra Fussen', '556-954-8781', 'Sweden');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('55', 'Jeanne Fike', '815-227-5826', 'Brazil');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('56', 'Jo ann Ingarfill', '327-357-9243', 'France');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('57', 'Caye Geale', '578-324-7573', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('58', 'Anny Tiddy', '701-447-1385', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('59', 'Rhetta Lilburne', '603-574-2789', 'Bosnia and Herzegovina');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('60', 'Reggy Brikner', '167-277-6149', 'Slovenia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('61', 'Nappie Airton', '222-578-1993', 'Poland');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('62', 'Donaugh Lemme', '677-540-8990', 'Russia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('63', 'Analiese Arnaud', '184-345-4682', 'Pakistan');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('64', 'Darla Newark', '647-284-3229', 'Belarus');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('65', 'Ariella Smeaton', '691-171-7041', 'Greece');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('66', 'Jose Marsy', '629-873-1200', 'Czech Republic');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('67', 'Koralle Jacombs', '702-697-8660', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('68', 'Salli Tatford', '902-302-0952', 'United Kingdom');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('69', 'Mal Yarnell', '153-555-5190', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('70', 'Dalis Yvens', '933-653-6453', 'Portugal');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('71', 'Fredrick Dabnor', '488-323-4708', 'Russia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('72', 'Shae Mose', '980-878-3657', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('73', 'Nicki Dyster', '198-314-7282', 'Indonesia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('74', 'Sissy Wiburn', '342-736-3912', 'Ecuador');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('75', 'Dari Ellcome', '792-329-1531', 'Russia');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('76', 'Tedie Panting', '603-854-2382', 'Sweden');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('77', 'Dorella Thowless', '556-636-7738', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('78', 'Elvyn Creavan', '921-970-3423', 'Czech Republic');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('79', 'Mariele Yukhnevich', '824-868-7149', 'Philippines');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('80', 'Maurizio Waber', '317-725-1659', 'Greece');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('81', 'Aurea Gooly', '291-967-8592', 'Ukraine');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('82', 'Barn Sears', '282-170-1494', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('83', 'Fianna Volant', '931-306-5795', 'France');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('84', 'Lind Scanlan', '600-463-2431', 'Madagascar');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('85', 'Marlow Wiggans', '937-152-9811', 'Argentina');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('86', 'Eugenia Danielkiewicz', '593-608-8692', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('87', 'Tailor Reis', '876-839-6741', 'Thailand');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('88', 'Kathe Dows', '176-827-5972', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('89', 'Stuart Upwood', '599-749-5984', 'Ukraine');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('90', 'Aldus Paulet', '549-876-8353', 'Kenya');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('91', 'Herb Hamber', '336-578-0160', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('92', 'Merna Lowerson', '716-533-8061', 'Albania');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('93', 'Teena Meiningen', '559-859-4439', 'Central African Republic');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('94', 'Deane Dutch', '558-181-7850', 'Israel');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('95', 'Chickie Munns', '127-277-7765', 'China');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('96', 'Ancell Dash', '529-485-2821', 'Peru');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('97', 'Daffy Whorlow', '613-830-4662', 'Mexico');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('98', 'Bunnie Petz', '145-360-6672', 'Mauritania');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('99', 'Babita Pryell', '582-235-0090', 'Netherlands');
INSERT INTO "main"."SponsorList" ("sponsorID", "sponsorName", "sponsorPhone", "sponsorAddress") VALUES ('100', 'Traver Jiran', '554-947-4404', 'Greece');